### ISSUE TITLE
Skin Can not display Menu/Nav with DNN8

### ISSUE THREAD

**Issue by khanhbis** [dnnconsulting/DnnC.Bootster#1]
I applied this skin for DNN8 but Menu/Nav can not displayed. 

How can i resolve it ? Many thanks for free

**Comment by dnnconsulting** [comment]
Hi,

could you supply more information on the problem...

Was it a fresh install, what version, the default language etc.

**Comment by dnnconsulting** [comment]
Found out what is causing this issue...
When installing Dnn 08.00.00, it creates a 'web.config' file in the root of the Portals folder

**/Portals/web.config**

Open this file and look for the following lines:

`<host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>`

`<add namespace="DotNetNuke.Web.Mvc.Helpers"/>`
`<add namespace="Dnn.Modules.DynamicContentViewer.Helpers"/>`

Take these out by doing the following:

`<!--<host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>-->`

`<!--<add namespace="DotNetNuke.Web.Mvc.Helpers"/>-->`
`<!--<add namespace="Dnn.Modules.DynamicContentViewer.Helpers"/>-->`

Save the file and the menus should display correctly.
