### ISSUE TITLE
Unable to install on vanilla DNN8 in Azure

### ISSUE THREAD

**Issue by SplatManDK** [dnnconsulting/DnnC.Bootster#10]
I am unable to install the skin in a freshly deployed vanilla instance of DNN in Azure. I get the following error:

A critical error has occurred. Please check the Event Viewer for further details.
close

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:ba5618f7-def6-45b0-8084-f4edf11c86b1
Server Name: RD00XXXD56BCX0

(servername altered to something similar; to keep my real server name out of this message)

I have attached the error from the DNN Event Log.

[DNN_skin_upload_error.txt](https://github.com/dnnconsulting/DnnC.Bootster/files/431266/DNN_skin_upload_error.txt)

**Comment by SplatManDK** [comment]
The error above is the result of downloading the wrong package (the Git Master ZIP file).

Installing the correct file from the Releases list still produces an error though; because the most recent DNN platform installer in Azure is apparently 07.01.02. Can't say I am much impressed by that, but it is what it is.

Update: After upgrading the portal in Azure, the skin npw installs correctly. This issue can be closed (but should perhaps stay visible to assist ither doing the same newbee mistakes as I did)

**Comment by dnnconsulting** [comment]
Hi SplatMan,

Good to hear that it all worked out in the end! You could have tried to change the dependency in the resource file but the skin was created for Dnn8.

Regards,

Geoff.
