### ISSUE TITLE
admin include missing

### ISSUE THREAD

**Issue by schotman** [dnnconsulting/DnnC.Bootster#14]
the includes/admin-page-header.ascx referenced in admin.ascx  is missing from the distribution

**Comment by dnnconsulting** [comment]
Hi Peter,

This is a known bug, just haven't had time to fix it.

See here: https://github.com/dnnconsulting/DnnC.Bootster/issues/6

**Comment by schotman** [comment]
Hi Jeff,

I did not know someone already reported this issue, because I did not look at the closed issues. As a matter of procedure, may be it is better not to close issues until they are really solved ;)

BTW Thanks for the skin, trying it out as we speak!
