### ISSUE TITLE
skin naming conventions

### ISSUE THREAD

**Issue by schotman** [dnnconsulting/DnnC.Bootster#16]
IMHO it is better to name the default skin "Default.ascx" instead of skin.ascx, when you don't want to have a name in the skin dropdown. Personally I do prefer a name, so I often use Main.ascx or something more descriptive like TwoColumns.ascx (allthough this is only true on desktop).

**Comment by dnnconsulting** [comment]
No problems Peter, 
When creating the themes I followed how the default themes (Gravity & Xcillion) were created as a standard. 

Will take your advice in future themes I create!

Geoff.
