### ISSUE TITLE
Custom CSS being overridden by bootster.css and grey.css

### ISSUE THREAD

**Issue by JaySMa** [dnnconsulting/DnnC.Bootster#18]
Hello..
I'm in the process of migrating a site from Wordpress over to DNN and have used Bootster as a start skin for this process.

There are some "news" buttons which are in a flex container, etc.  The flex container works fine, but the internal styles of the internal buttons is being over-ridden by bootster.css and grey.css.

Within the skin file, I've tried adding Priority's to the DNNCSSInclude files and making my custom CSS a priority of 100, bootster.css an 11 and gray.css a 12 but on screen refresh, my custom settings are still being over-ridden.

Why is this occurring?  Of course, if I REM out the grey and bootster entries in the skin file, my settings then are overridden by bootstrap.css.  Any ideas?  Thanks..

**Comment by JaySMa** [comment]
I've even set my CSS file with a priority of 100 (should be above EVERYTHING) and it's still not working.  Have tried placing it BELOW the grey.css listing within the skin and in the code, it shows my CSS being listed as the last CSS loaded; but it's still being overwritten.

Have event tried [http://www.dnnsoftware.com/wiki/client-resource-management-api](url) and nothing here helped either.

Thanks..

**Comment by dnnconsulting** [comment]
JaySMa,

Try and adding your custom css to the bottom of the 'grey.css' file and not using the priority of the css files.

Also make sure that you change the rest of the skin files to use the 'grey.css' file.

Geoff.

**Comment by dnnconsulting** [comment]
also, I don't know if you realize this but there is a newer version of the DnnBootster theme called DnnBootsterV2 which can be found here:

www.DnnBootster.com

**Comment by JaySMa** [comment]
Hello.. I believe I'm using the latest DNNBooster version.

But after a reboot of both the server and the my PC at EOD, next morning there wasn't any other issue.

Not entirely sure.

Thank you for assistance..
