### ISSUE TITLE
Getting missing admin-page-header.ascx ... 

### ISSUE THREAD

**Issue by JaySMa** [dnnconsulting/DnnC.Bootster#6]
Using DnnC_BootstrapHelpers and when going into editing settings, at the top DNN states it's missing the admin-page-header.ascx.

The file is not located in the includes folder.

This is version 1.00.03.

Could Not Load Theme: /Portals/0/Skins/DnnBootster/Admin.ascx, Error: Could not find file 'C:\Websites\DNN Platform\Portals\0\Skins\DnnBootster\includes\admin-page-header.ascx'.

**Comment by JaySMa** [comment]
Any update to this?  I've tried the latest version and it too is having this issue.

Thanks..

**Comment by dnnconsulting** [comment]
Jaysma,

look in the admin.ascx and navigate down to line 40, look for the line:

`<!--#include file = "includes/admin-page-header.ascx" -->`

change this to 

`<!--#include file = "includes/page-header.ascx" -->`

hopefully this will sort your problem out.

DnnConsulting

**Comment by JaySMa** [comment]
What it should be edited to has been cut out by the system?

Thanks..

**Comment by dnnconsulting** [comment]
Should be visible now

**Comment by JaySMa** [comment]
Great, thank you and this resolved the issue.
