### ISSUE TITLE
dropdown active class not being applied?

### ISSUE THREAD

**Issue by djamell** [dnnconsulting/DnnC.Bootster#7]
When a root menu item is selected it gets the "active" class added to the List Element

But if the page selected is a submenu the "active" class is not applied to the root menu element.

Looking at the nav.cshtml it looks like it is supposed to work, but doesn't.

Am I missing something?

**Comment by djamell** [comment]
I found what I was looking for by altering the settings in the jquery.smartmenus.js file.

At line 1207 and 1208 are the items markCurrentItem and markCurrentTree that control the "breadcrumb" behavior.

Great Skin!  Thank you so much for sharing.

**Comment by dnnconsulting** [comment]
Hi djameel,

Glad to hear you got it to work the way you wanted!

Regards,
Geoff
