### ISSUE TITLE
Creating install package

### ISSUE THREAD

**Issue by SindreSB** [dnnconsulting/DnnC.Bootster#8]
Hi, 

I'm new to DNN and how the packing of these extensions/themes work. I want to modify this theme a little before i use it. After I've downloaded the source and done my edits, how do I package it to an install package?

**Comment by dnnconsulting** [comment]
Hi,

If you are going to change the theme it might be easier to first install the theme locally then do your changes.

To package the theme I would suggest you to use the DnnBootster install package as an example. Un-zip it and have a look to see how its done. The main thing you should be looking at is the 'DnnBootster.dnn' file.

I would also suggest you to have a look at these two resourses as well:

http://www.dnnsoftware.com/docs/designers/extensions/pack-extension.html
http://www.dnnsoftware.com/community-blog/cid/132068/dotnetnuke-skinning-101-part-4

Regards,

Geoff.
